### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MasterOfTheTiger** [edxtech/scratchnetworkclient#1]
What is the license for this program? It is not open source unless it is licensed.

**Comment by MasterOfTheTiger** [comment]
Oh and I need to mention you since you aren’t watching this repo. @Edxt

**Comment by MasterOfTheTiger** [comment]
@edxtech I mean

**Comment by ed6767** [comment]
I am watching and have resolved.

**Comment by MasterOfTheTiger** [comment]
Okay great!
